services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=sua-senhaaqui#789
        - MSSQL_DATABASE=ThaVigil 
    ports:
        - "1433:1433"
    volumes:
        - D:\DATA\volumes\sqlserver:/var/opt/mssql/data
  tha.api:
    image: ${DOCKER_REGISTRY-}thaapi
    build:
      context: .
      dockerfile: src/THA.API/Dockerfile

    